spring:
  application:
      name: 'Welcome ACL'
  docker:
    compose:
      skip:
        in-tests: true
      start:
        log-level: warn
      lifecycle-management: start_only
  data:
    redis:
      connect-timeout: 5s

logging:
  level:
    root: warn
    me:
      riddle:
        boot:
          redis: debug
    org:
      springframework:
        boot:
          docker: warn
          zipkin: info
        data:
          redis:
            stream: info


management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    defaults:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: threaddump, heapdump
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
        add-additional-paths: true
      show-components: always
    env:
      enabled: true
      show-values: always
    info:
      enabled: true
    conditions:
      enabled: true
    configprops:
      enabled: true
      show-values: always
    auditevents:
      enabled: true
    metrics:
      enabled: true
    beans:
      enabled: true
    caches:
      enabled: true
    logfile:
      enabled: true
    loggers:
      enabled: true
    heapdump:
      enabled: false
    threaddump:
      enabled: false
    httpexchanges:
      enabled: true
    integrationgraph:
      enabled: true
    scheduledtasks:
      enabled: true
    quartz:
      enabled: true
      show-values: always
    shutdown:
      enabled: true